package com.dating.reveal.main;

public class SocChatConst {
	
	//socketIO event
	public	static final String CHAT = "chat_message";
	public	static final String JOIN = "join_channel";
	public	static final String USER_LIST = "user_list";
	public	static final String USER_JOIN = "user_joined";
	public	static final String USER_LEFT = "user_left";
	public	static final String CACHED_MSG = "cached_messages";
	public	static final String WHISPER = "whisper";
	public  static final String WHISPER_REQ = "whisper_request";
	public  static final String WHISPER_ACCEPT = "whisper_accept";
	public  static final String WHISPER_CANCEL = "whisper_cancel";
	
	// Contact table
	public static final String NICKNAME = "nickname";
	public static final String EMAIL = "email";
	public static final String PASSWORD = "password";
	public static final String AVATAR = "avatar";
	public static final String THUMBNAIL = "thumbnail";
	public static final String STREAM_KEY = "streamkey";
	public static final String USER_ID = "user_id";
	public static final String REMEMBERME = "remember_me";
	public static final String GENDER = "gender";
	public static final String CHANNELNAME = "channelname";
	public static final String HEADLINE = "headline";
	public static final String COUNTRY = "country";
	public static final String STATE = "state";
	public static final String LANGUAGE = "language";
	
    public static final String[]  Country = {
    		"{\"code\":\"AF\", \"name\": \"Afghanistan\"}",
    		"{\"code\":\"AX\", \"name\": \"Åland Islands\"}",
    		"{\"code\":\"AL\", \"name\": \"Albania\"}",
    		"{\"code\":\"DZ\", \"name\": \"Algeria\"}",
    		"{\"code\":\"AS\", \"name\": \"American Samoa\"}",
    		"{\"code\":\"AD\", \"name\": \"Andorra\"}",
    		"{\"code\":\"AO\", \"name\": \"Angola\"}",
    		"{\"code\":\"AI\", \"name\": \"Anguilla\"}",
    		"{\"code\":\"AQ\", \"name\": \"Antarctica\"}",
    		"{\"code\":\"AG\", \"name\": \"Antigua and Barbuda\"}",
    		"{\"code\":\"AR\", \"name\": \"Argentina\"}",
    		"{\"code\":\"AM\", \"name\": \"Armenia\"}",
    		"{\"code\":\"AW\", \"name\": \"Aruba\"}",
    		"{\"code\":\"AU\", \"name\": \"Australia\"}",
    		"{\"code\":\"AT\", \"name\": \"Austria\"}",
    		"{\"code\":\"AZ\", \"name\": \"Azerbaijan\"}",
    		"{\"code\":\"BS\", \"name\": \"Bahamas\"}",
    		"{\"code\":\"BH\", \"name\": \"Bahrain\"}",
    		"{\"code\":\"BD\", \"name\": \"Bangladesh\"}",
    		"{\"code\":\"BB\", \"name\": \"Barbados\"}",
    		"{\"code\":\"BY\", \"name\": \"Belarus\"}",
    		"{\"code\":\"BE\", \"name\": \"Belgium\"}",
    		"{\"code\":\"BZ\", \"name\": \"Belize\"}",
    		"{\"code\":\"BJ\", \"name\": \"Benin\"}",
    		"{\"code\":\"BM\", \"name\": \"Bermuda\"}",
    		"{\"code\":\"BT\", \"name\": \"Bhutan\"}",
    		"{\"code\":\"BO\", \"name\": \"Bolivia, Plurinational State of\"}",
    		"{\"code\":\"BQ\", \"name\": \"Bonaire, Sint Eustatius and Saba\"}",
    		"{\"code\":\"BA\", \"name\": \"Bosnia and Herzegovina\"}",
    		"{\"code\":\"BW\", \"name\": \"Botswana\"}",
    		"{\"code\":\"BV\", \"name\": \"Bouvet Island\"}",
    		"{\"code\":\"BR\", \"name\": \"Brazil\"}",
    		"{\"code\":\"IO\", \"name\": \"British Indian Ocean Territory\"}",
    		"{\"code\":\"BN\", \"name\": \"Brunei Darussalam\"}",
    		"{\"code\":\"BG\", \"name\": \"Bulgaria\"}",
    		"{\"code\":\"BF\", \"name\": \"Burkina Faso\"}",
    		"{\"code\":\"BI\", \"name\": \"Burundi\"}",
    		"{\"code\":\"KH\", \"name\": \"Cambodia\"}",
    		"{\"code\":\"CM\", \"name\": \"Cameroon\"}",
    		"{\"code\":\"CA\", \"name\": \"Canada\"}",
    		"{\"code\":\"CV\", \"name\": \"Cape Verde\"}",
    		"{\"code\":\"KY\", \"name\": \"Cayman Islands\"}",
    		"{\"code\":\"CF\", \"name\": \"Central African Republic\"}",
    		"{\"code\":\"TD\", \"name\": \"Chad\"}",
    		"{\"code\":\"CL\", \"name\": \"Chile\"}",
    		"{\"code\":\"CN\", \"name\": \"China\"}",
    		"{\"code\":\"CX\", \"name\": \"Christmas Island\"}",
    		"{\"code\":\"CC\", \"name\": \"Cocos (Keeling) Islands\"}",
    		"{\"code\":\"CO\", \"name\": \"Colombia\"}",
    		"{\"code\":\"KM\", \"name\": \"Comoros\"}",
    		"{\"code\":\"CG\", \"name\": \"Congo\"}",
    		"{\"code\":\"CD\", \"name\": \"Congo, the Democratic Republic of the\"}",
    		"{\"code\":\"CK\", \"name\": \"Cook Islands\"}",
    		"{\"code\":\"CR\", \"name\": \"Costa Rica\"}",
    		"{\"code\":\"CI\", \"name\": \"Côte d'Ivoire\"}",
    		"{\"code\":\"HR\", \"name\": \"Croatia\"}",
    		"{\"code\":\"CU\", \"name\": \"Cuba\"}",
    		"{\"code\":\"CW\", \"name\": \"Curaçao\"}",
    		"{\"code\":\"CY\", \"name\": \"Cyprus\"}",
    		"{\"code\":\"CZ\", \"name\": \"Czech Republic\"}",
    		"{\"code\":\"DK\", \"name\": \"Denmark\"}",
    		"{\"code\":\"DJ\", \"name\": \"Djibouti\"}",
    		"{\"code\":\"DM\", \"name\": \"Dominica\"}",
    		"{\"code\":\"DO\", \"name\": \"Dominican Republic\"}",
    		"{\"code\":\"EC\", \"name\": \"Ecuador\"}",
    		"{\"code\":\"EG\", \"name\": \"Egypt\"}",
    		"{\"code\":\"SV\", \"name\": \"El Salvador\"}",
    		"{\"code\":\"GQ\", \"name\": \"Equatorial Guinea\"}",
    		"{\"code\":\"ER\", \"name\": \"Eritrea\"}",
    		"{\"code\":\"EE\", \"name\": \"Estonia\"}",
    		"{\"code\":\"ET\", \"name\": \"Ethiopia\"}",
    		"{\"code\":\"FK\", \"name\": \"Falkland Islands (Malvinas)\"}",
    		"{\"code\":\"FO\", \"name\": \"Faroe Islands\"}",
    		"{\"code\":\"FJ\", \"name\": \"Fiji\"}",
    		"{\"code\":\"FI\", \"name\": \"Finland\"}",
    		"{\"code\":\"FR\", \"name\": \"France\"}",
    		"{\"code\":\"GF\", \"name\": \"French Guiana\"}",
    		"{\"code\":\"PF\", \"name\": \"French Polynesia\"}",
    		"{\"code\":\"TF\", \"name\": \"French Southern Territories\"}",
    		"{\"code\":\"GA\", \"name\": \"Gabon\"}",
    		"{\"code\":\"GM\", \"name\": \"Gambia\"}",
    		"{\"code\":\"GE\", \"name\": \"Georgia\"}",
    		"{\"code\":\"DE\", \"name\": \"Germany\"}",
    		"{\"code\":\"GH\", \"name\": \"Ghana\"}",
    		"{\"code\":\"GI\", \"name\": \"Gibraltar\"}",
    		"{\"code\":\"GR\", \"name\": \"Greece\"}",
    		"{\"code\":\"GL\", \"name\": \"Greenland\"}",
    		"{\"code\":\"GD\", \"name\": \"Grenada\"}",
    		"{\"code\":\"GP\", \"name\": \"Guadeloupe\"}",
    		"{\"code\":\"GU\", \"name\": \"Guam\"}",
    		"{\"code\":\"GT\", \"name\": \"Guatemala\"}",
    		"{\"code\":\"GG\", \"name\": \"Guernsey\"}",
    		"{\"code\":\"GN\", \"name\": \"Guinea\"}",
    		"{\"code\":\"GW\", \"name\": \"Guinea-Bissau\"}",
    		"{\"code\":\"GY\", \"name\": \"Guyana\"}",
    		"{\"code\":\"HT\", \"name\": \"Haiti\"}",
    		"{\"code\":\"HM\", \"name\": \"Heard Island and McDonald Islands\"}",
    		"{\"code\":\"VA\", \"name\": \"Holy See (Vatican City State)\"}",
    		"{\"code\":\"HN\", \"name\": \"Honduras\"}",
    		"{\"code\":\"HK\", \"name\": \"Hong Kong\"}",
    		"{\"code\":\"HU\", \"name\": \"Hungary\"}",
    		"{\"code\":\"IS\", \"name\": \"Iceland\"}",
    		"{\"code\":\"IN\", \"name\": \"India\"}",
    		"{\"code\":\"ID\", \"name\": \"Indonesia\"}",
    		"{\"code\":\"IR\", \"name\": \"Iran, Islamic Republic of\"}",
    		"{\"code\":\"IQ\", \"name\": \"Iraq\"}",
    		"{\"code\":\"IE\", \"name\": \"Ireland\"}",
    		"{\"code\":\"IM\", \"name\": \"Isle of Man\"}",
    		"{\"code\":\"IL\", \"name\": \"Israel\"}",
    		"{\"code\":\"IT\", \"name\": \"Italy\"}",
    		"{\"code\":\"JM\", \"name\": \"Jamaica\"}",
    		"{\"code\":\"JP\", \"name\": \"Japan\"}",
    		"{\"code\":\"JE\", \"name\": \"Jersey\"}",
    		"{\"code\":\"JO\", \"name\": \"Jordan\"}",
    		"{\"code\":\"KZ\", \"name\": \"Kazakhstan\"}",
    		"{\"code\":\"KE\", \"name\": \"Kenya\"}",
    		"{\"code\":\"KI\", \"name\": \"Kiribati\"}",
    		"{\"code\":\"KP\", \"name\": \"Korea, Democratic People's Republic of\"}",
    		"{\"code\":\"KR\", \"name\": \"Korea, Republic of\"}",
    		"{\"code\":\"KW\", \"name\": \"Kuwait\"}",
    		"{\"code\":\"KG\", \"name\": \"Kyrgyzstan\"}",
    		"{\"code\":\"LA\", \"name\": \"Lao People's Democratic Republic\"}",
    		"{\"code\":\"LV\", \"name\": \"Latvia\"}",
    		"{\"code\":\"LB\", \"name\": \"Lebanon\"}",
    		"{\"code\":\"LS\", \"name\": \"Lesotho\"}",
    		"{\"code\":\"LR\", \"name\": \"Liberia\"}",
    		"{\"code\":\"LY\", \"name\": \"Libya\"}",
    		"{\"code\":\"LI\", \"name\": \"Liechtenstein\"}",
    		"{\"code\":\"LT\", \"name\": \"Lithuania\"}",
    		"{\"code\":\"LU\", \"name\": \"Luxembourg\"}",
    		"{\"code\":\"MO\", \"name\": \"Macao\"}",
    		"{\"code\":\"MK\", \"name\": \"Macedonia, the former Yugoslav Republic of\"}",
    		"{\"code\":\"MG\", \"name\": \"Madagascar\"}",
    		"{\"code\":\"MW\", \"name\": \"Malawi\"}",
    		"{\"code\":\"MY\", \"name\": \"Malaysia\"}",
    		"{\"code\":\"MV\", \"name\": \"Maldives\"}",
    		"{\"code\":\"ML\", \"name\": \"Mali\"}",
    		"{\"code\":\"MT\", \"name\": \"Malta\"}",
    		"{\"code\":\"MH\", \"name\": \"Marshall Islands\"}",
    		"{\"code\":\"MQ\", \"name\": \"Martinique\"}",
    		"{\"code\":\"MR\", \"name\": \"Mauritania\"}",
    		"{\"code\":\"MU\", \"name\": \"Mauritius\"}",
    		"{\"code\":\"YT\", \"name\": \"Mayotte\"}",
    		"{\"code\":\"MX\", \"name\": \"Mexico\"}",
    		"{\"code\":\"FM\", \"name\": \"Micronesia, Federated States of\"}",
    		"{\"code\":\"MD\", \"name\": \"Moldova, Republic of\"}",
    		"{\"code\":\"MC\", \"name\": \"Monaco\"}",
    		"{\"code\":\"MN\", \"name\": \"Mongolia\"}",
    		"{\"code\":\"ME\", \"name\": \"Montenegro\"}",
    		"{\"code\":\"MS\", \"name\": \"Montserrat\"}",
    		"{\"code\":\"MA\", \"name\": \"Morocco\"}",
    		"{\"code\":\"MZ\", \"name\": \"Mozambique\"}",
    		"{\"code\":\"MM\", \"name\": \"Myanmar\"}",
    		"{\"code\":\"NA\", \"name\": \"Namibia\"}",
    		"{\"code\":\"NR\", \"name\": \"Nauru\"}",
    		"{\"code\":\"NP\", \"name\": \"Nepal\"}",
    		"{\"code\":\"NL\", \"name\": \"Netherlands\"}",
    		"{\"code\":\"NC\", \"name\": \"New Caledonia\"}",
    		"{\"code\":\"NZ\", \"name\": \"New Zealand\"}",
    		"{\"code\":\"NI\", \"name\": \"Nicaragua\"}",
    		"{\"code\":\"NE\", \"name\": \"Niger\"}",
    		"{\"code\":\"NG\", \"name\": \"Nigeria\"}",
    		"{\"code\":\"NU\", \"name\": \"Niue\"}",
    		"{\"code\":\"NF\", \"name\": \"Norfolk Island\"}",
    		"{\"code\":\"MP\", \"name\": \"Northern Mariana Islands\"}",
    		"{\"code\":\"NO\", \"name\": \"Norway\"}",
    		"{\"code\":\"OM\", \"name\": \"Oman\"}",
    		"{\"code\":\"PK\", \"name\": \"Pakistan\"}",
    		"{\"code\":\"PW\", \"name\": \"Palau\"}",
    		"{\"code\":\"PS\", \"name\": \"Palestine, State of\"}",
    		"{\"code\":\"PA\", \"name\": \"Panama\"}",
    		"{\"code\":\"PG\", \"name\": \"Papua New Guinea\"}",
    		"{\"code\":\"PY\", \"name\": \"Paraguay\"}",
    		"{\"code\":\"PE\", \"name\": \"Peru\"}",
    		"{\"code\":\"PH\", \"name\": \"Philippines\"}",
    		"{\"code\":\"PN\", \"name\": \"Pitcairn\"}",
    		"{\"code\":\"PL\", \"name\": \"Poland\"}",
    		"{\"code\":\"PT\", \"name\": \"Portugal\"}",
    		"{\"code\":\"PR\", \"name\": \"Puerto Rico\"}",
    		"{\"code\":\"QA\", \"name\": \"Qatar\"}",
    		"{\"code\":\"RE\", \"name\": \"Réunion\"}",
    		"{\"code\":\"RO\", \"name\": \"Romania\"}",
    		"{\"code\":\"RU\", \"name\": \"Russian Federation\"}",
    		"{\"code\":\"RW\", \"name\": \"Rwanda\"}",
    		"{\"code\":\"BL\", \"name\": \"Saint Barthélemy\"}",
    		"{\"code\":\"SH\", \"name\": \"Saint Helena, Ascension and Tristan da Cunha\"}",
    		"{\"code\":\"KN\", \"name\": \"Saint Kitts and Nevis\"}",
    		"{\"code\":\"LC\", \"name\": \"Saint Lucia\"}",
    		"{\"code\":\"MF\", \"name\": \"Saint Martin (French part)\"}",
    		"{\"code\":\"PM\", \"name\": \"Saint Pierre and Miquelon\"}",
    		"{\"code\":\"VC\", \"name\": \"Saint Vincent and the Grenadines\"}",
    		"{\"code\":\"WS\", \"name\": \"Samoa\"}",
    		"{\"code\":\"SM\", \"name\": \"San Marino\"}",
    		"{\"code\":\"ST\", \"name\": \"Sao Tome and Principe\"}",
    		"{\"code\":\"SA\", \"name\": \"Saudi Arabia\"}",
    		"{\"code\":\"SN\", \"name\": \"Senegal\"}",
    		"{\"code\":\"RS\", \"name\": \"Serbia\"}",
    		"{\"code\":\"SC\", \"name\": \"Seychelles\"}",
    		"{\"code\":\"SL\", \"name\": \"Sierra Leone\"}",
    		"{\"code\":\"SG\", \"name\": \"Singapore\"}",
    		"{\"code\":\"SX\", \"name\": \"Sint Maarten (Dutch part)\"}",
    		"{\"code\":\"SK\", \"name\": \"Slovakia\"}",
    		"{\"code\":\"SI\", \"name\": \"Slovenia\"}",
    		"{\"code\":\"SB\", \"name\": \"Solomon Islands\"}",
    		"{\"code\":\"SO\", \"name\": \"Somalia\"}",
    		"{\"code\":\"ZA\", \"name\": \"South Africa\"}",
    		"{\"code\":\"GS\", \"name\": \"South Georgia and the South Sandwich Islands\"}",
    		"{\"code\":\"SS\", \"name\": \"South Sudan\"}",
    		"{\"code\":\"ES\", \"name\": \"Spain\"}",
    		"{\"code\":\"LK\", \"name\": \"Sri Lanka\"}",
    		"{\"code\":\"SD\", \"name\": \"Sudan\"}",
    		"{\"code\":\"SR\", \"name\": \"Suriname\"}",
    		"{\"code\":\"SJ\", \"name\": \"Svalbard and Jan Mayen\"}",
    		"{\"code\":\"SZ\", \"name\": \"Swaziland\"}",
    		"{\"code\":\"SE\", \"name\": \"Sweden\"}",
    		"{\"code\":\"CH\", \"name\": \"Switzerland\"}",
    		"{\"code\":\"SY\", \"name\": \"Syrian Arab Republic\"}",
    		"{\"code\":\"TW\", \"name\": \"Taiwan, Province of China\"}",
    		"{\"code\":\"TJ\", \"name\": \"Tajikistan\"}",
    		"{\"code\":\"TZ\", \"name\": \"Tanzania, United Republic of\"}",
    		"{\"code\":\"TH\", \"name\": \"Thailand\"}",
    		"{\"code\":\"TL\", \"name\": \"Timor-Leste\"}",
    		"{\"code\":\"TG\", \"name\": \"Togo\"}",
    		"{\"code\":\"TK\", \"name\": \"Tokelau\"}",
    		"{\"code\":\"TO\", \"name\": \"Tonga\"}",
    		"{\"code\":\"TT\", \"name\": \"Trinidad and Tobago\"}",
    		"{\"code\":\"TN\", \"name\": \"Tunisia\"}",
    		"{\"code\":\"TR\", \"name\": \"Turkey\"}",
    		"{\"code\":\"TM\", \"name\": \"Turkmenistan\"}",
    		"{\"code\":\"TC\", \"name\": \"Turks and Caicos Islands\"}",
    		"{\"code\":\"TV\", \"name\": \"Tuvalu\"}",
    		"{\"code\":\"UG\", \"name\": \"Uganda\"}",
    		"{\"code\":\"UA\", \"name\": \"Ukraine\"}",
    		"{\"code\":\"AE\", \"name\": \"United Arab Emirates\"}",
    		"{\"code\":\"GB\", \"name\": \"United Kingdom\"}",
    		"{\"code\":\"US\", \"name\": \"United States\"}",
    		"{\"code\":\"UM\", \"name\": \"United States Minor Outlying Islands\"}",
    		"{\"code\":\"UY\", \"name\": \"Uruguay\"}",
    		"{\"code\":\"UZ\", \"name\": \"Uzbekistan\"}",
    		"{\"code\":\"VU\", \"name\": \"Vanuatu\"}",
    		"{\"code\":\"VE\", \"name\": \"Venezuela, Bolivarian Republic of\"}",
    		"{\"code\":\"VN\", \"name\": \"Viet Nam\"}",
    		"{\"code\":\"VG\", \"name\": \"Virgin Islands, British\"}",
    		"{\"code\":\"VI\", \"name\": \"Virgin Islands, U.S.\"}",
    		"{\"code\":\"WF\", \"name\": \"Wallis and Futuna\"}",
    		"{\"code\":\"EH\", \"name\": \"Western Sahara\"}",
    		"{\"code\":\"YE\", \"name\": \"Yemen\"}",
    		"{\"code\":\"ZM\", \"name\": \"Zambia\"}"
    };
    
    public static final String[]  State = {
    		"{\"code\":\"IN-AN\", \"name\":\"Andaman and Nicobar Islands\"}",
    		"{\"code\":\"IN-AP\", \"name\":\"Andhra Pradesh\"}",
    		"{\"code\":\"IN-AR\", \"name\":\"Arunachal Pradesh\"}",
    		"{\"code\":\"IN-AS\", \"name\":\"Assam\"}",
    		"{\"code\":\"IN-BR\", \"name\":\"Bihar\"}",
    		"{\"code\":\"IN-CH\", \"name\":\"Chandigarh\"}",
    		"{\"code\":\"IN-CT\", \"name\":\"Chhattisgarh\"}",
    		"{\"code\":\"IN-DN\", \"name\":\"Dadra and Nagar Haveli\"}",
    		"{\"code\":\"IN-DD\", \"name\":\"Daman and Diu\"}",
    		"{\"code\":\"IN-DL\", \"name\":\"Delhi\"}",
    		"{\"code\":\"IN-GA\", \"name\":\"Goa\"}",
    		"{\"code\":\"IN-GJ\", \"name\":\"Gujarat\"}",
    		"{\"code\":\"IN-HR\", \"name\":\"Haryana\"}",
    		"{\"code\":\"IN-HP\", \"name\":\"Himachal Pradesh\"}",
    		"{\"code\":\"IN-JK\", \"name\":\"Jammu and Kashmir\"}",
    		"{\"code\":\"IN-JH\", \"name\":\"Jharkhand\"}",
    		"{\"code\":\"IN-KA\", \"name\":\"Karnataka\"}",
    		"{\"code\":\"IN-KL\", \"name\":\"Kerala\"}",
    		"{\"code\":\"IN-LD\", \"name\":\"Lakshadweep\"}",
    		"{\"code\":\"IN-MP\", \"name\":\"Madhya Pradesh\"}",
    		"{\"code\":\"IN-MH\", \"name\":\"Maharashtra\"}",
    		"{\"code\":\"IN-MN\", \"name\":\"Manipur\"}",
    		"{\"code\":\"IN-ML\", \"name\":\"Meghalaya\"}",
    		"{\"code\":\"IN-MZ\", \"name\":\"Mizoram\"}",
    		"{\"code\":\"IN-NL\", \"name\":\"Nagaland\"}",
    		"{\"code\":\"IN-OR\", \"name\":\"Orissa\"}",
    		"{\"code\":\"IN-PY\", \"name\":\"Pondicherry\"}",
    		"{\"code\":\"IN-PB\", \"name\":\"Punjab\"}",
    		"{\"code\":\"IN-RJ\", \"name\":\"Rajasthan\"}",
    		"{\"code\":\"IN-SK\", \"name\":\"Sikkim\"}",
    		"{\"code\":\"IN-TN\", \"name\":\"Tamil Nadu\"}",
    		"{\"code\":\"IN-TR\", \"name\":\"Tripura\"}",
    		"{\"code\":\"IN-UP\", \"name\":\"Uttar Pradesh\"}",
    		"{\"code\":\"IN-UT\", \"name\":\"Uttaranchal\"}",
    		"{\"code\":\"IN-WB\", \"name\":\"West Bengal\"}"
    };
    
    public static final String[]  Language = {
    		"{\"code\":\"aa\", \"name\":\"Afar\"}",
    		"{\"code\":\"ab\", \"name\":\"Abkhaz\"}",
    		"{\"code\":\"ae\", \"name\":\"Avestan\"}",
    		"{\"code\":\"af\", \"name\":\"Afrikaans\"}",
    		"{\"code\":\"ak\", \"name\":\"Akan\"}",
    		"{\"code\":\"am\", \"name\":\"Amharic\"}",
    		"{\"code\":\"an\", \"name\":\"Aragonese\"}",
    		"{\"code\":\"ar\", \"name\":\"Arabic\"}",
    		"{\"code\":\"as\", \"name\":\"Assamese\"}",
    		"{\"code\":\"av\", \"name\":\"Avaric\"}",
    		"{\"code\":\"ay\", \"name\":\"Aymara\"}",
    		"{\"code\":\"az\", \"name\":\"Azerbaijani\"}",
    		"{\"code\":\"ba\", \"name\":\"Bashkir\"}",
    		"{\"code\":\"be\", \"name\":\"Belarusian\"}",
    		"{\"code\":\"bg\", \"name\":\"Bulgarian\"}",
    		"{\"code\":\"bh\", \"name\":\"Bihari\"}",
    		"{\"code\":\"bi\", \"name\":\"Bislama\"}",
    		"{\"code\":\"bm\", \"name\":\"Bambara\"}",
    		"{\"code\":\"bn\", \"name\":\"Bengali\"}",
    		"{\"code\":\"bo\", \"name\":\"Tibetan Standard, Tibetan, Central\"}",
    		"{\"code\":\"br\", \"name\":\"Breton\"}",
    		"{\"code\":\"bs\", \"name\":\"Bosnian\"}",
    		"{\"code\":\"ca\", \"name\":\"Catalan; Valencian\"}",
    		"{\"code\":\"ce\", \"name\":\"Chechen\"}",
    		"{\"code\":\"ch\", \"name\":\"Chamorro\"}",
    		"{\"code\":\"co\", \"name\":\"Corsican\"}",
    		"{\"code\":\"cr\", \"name\":\"Cree\"}",
    		"{\"code\":\"cs\", \"name\":\"Czech\"}",
    		"{\"code\":\"cu\", \"name\":\"Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic\"}",
    		"{\"code\":\"cv\", \"name\":\"Chuvash\"}",
    		"{\"code\":\"cy\", \"name\":\"Welsh\"}",
    		"{\"code\":\"da\", \"name\":\"Danish\"}",
    		"{\"code\":\"de\", \"name\":\"German\"}",
    		"{\"code\":\"dv\", \"name\":\"Divehi; Dhivehi; Maldivian;\"}",
    		"{\"code\":\"dz\", \"name\":\"Dzongkha\"}",
    		"{\"code\":\"ee\", \"name\":\"Ewe\"}",
    		"{\"code\":\"el\", \"name\":\"Greek, Modern\"}",
    		"{\"code\":\"en\", \"name\":\"English\"}",
    		"{\"code\":\"eo\", \"name\":\"Esperanto\"}",
    		"{\"code\":\"es\", \"name\":\"Spanish; Castilian\"}",
    		"{\"code\":\"et\", \"name\":\"Estonian\"}",
    		"{\"code\":\"eu\", \"name\":\"Basque\"}",
    		"{\"code\":\"fa\", \"name\":\"Persian\"}",
    		"{\"code\":\"ff\", \"name\":\"Fula; Fulah; Pulaar; Pular\"}",
    		"{\"code\":\"fi\", \"name\":\"Finnish\"}",
    		"{\"code\":\"fj\", \"name\":\"Fijian\"}",
    		"{\"code\":\"fo\", \"name\":\"Faroese\"}",
    		"{\"code\":\"fr\", \"name\":\"French\"}",
    		"{\"code\":\"fy\", \"name\":\"Western Frisian\"}",
    		"{\"code\":\"ga\", \"name\":\"Irish\"}",
    		"{\"code\":\"gd\", \"name\":\"Scottish Gaelic; Gaelic\"}",
    		"{\"code\":\"gl\", \"name\":\"Galician\"}",
    		"{\"code\":\"gn\", \"name\":\"GuaranÅ&shy;\"}",
    		"{\"code\":\"gu\", \"name\":\"Gujarati\"}",
    		"{\"code\":\"gv\", \"name\":\"Manx\"}",
    		"{\"code\":\"ha\", \"name\":\"Hausa\"}",
    		"{\"code\":\"he\", \"name\":\"Hebrew (modern)\"}",
    		"{\"code\":\"hi\", \"name\":\"Hindi\"}",
    		"{\"code\":\"ho\", \"name\":\"Hiri Motu\"}",
    		"{\"code\":\"hr\", \"name\":\"Croatian\"}",
    		"{\"code\":\"ht\", \"name\":\"Haitian; Haitian Creole\"}",
    		"{\"code\":\"hu\", \"name\":\"Hungarian\"}",
    		"{\"code\":\"hy\", \"name\":\"Armenian\"}",
    		"{\"code\":\"hz\", \"name\":\"Herero\"}",
    		"{\"code\":\"ia\", \"name\":\"Interlingua\"}",
    		"{\"code\":\"id\", \"name\":\"Indonesian\"}",
    		"{\"code\":\"ie\", \"name\":\"Interlingue\"}",
    		"{\"code\":\"ig\", \"name\":\"Igbo\"}",
    		"{\"code\":\"ii\", \"name\":\"Nuosu\"}",
    		"{\"code\":\"ik\", \"name\":\"Inupiaq\"}",
    		"{\"code\":\"io\", \"name\":\"Ido\"}",
    		"{\"code\":\"is\", \"name\":\"Icelandic\"}",
    		"{\"code\":\"it\", \"name\":\"Italian\"}",
    		"{\"code\":\"iu\", \"name\":\"Inuktitut\"}",
    		"{\"code\":\"ja\", \"name\":\"Japanese (ja)\"}",
    		"{\"code\":\"jv\", \"name\":\"Javanese (jv)\"}",
    		"{\"code\":\"ka\", \"name\":\"Georgian\"}",
    		"{\"code\":\"kg\", \"name\":\"Kongo\"}",
    		"{\"code\":\"ki\", \"name\":\"Kikuyu, Gikuyu\"}",
    		"{\"code\":\"kj\", \"name\":\"Kwanyama, Kuanyama\"}",
    		"{\"code\":\"kk\", \"name\":\"Kazakh\"}",
    		"{\"code\":\"kl\", \"name\":\"Kalaallisut, Greenlandic\"}",
    		"{\"code\":\"km\", \"name\":\"Khmer\"}",
    		"{\"code\":\"kn\", \"name\":\"Kannada\"}",
    		"{\"code\":\"ko\", \"name\":\"Korean\"}",
    		"{\"code\":\"kr\", \"name\":\"Kanuri\"}",
    		"{\"code\":\"ks\", \"name\":\"Kashmiri\"}",
    		"{\"code\":\"ku\", \"name\":\"Kurdish\"}",
    		"{\"code\":\"kv\", \"name\":\"Komi\"}",
    		"{\"code\":\"kw\", \"name\":\"Cornish\"}",
    		"{\"code\":\"ky\", \"name\":\"Kirghiz, Kyrgyz\"}",
    		"{\"code\":\"la\", \"name\":\"Latin\"}",
    		"{\"code\":\"lb\", \"name\":\"Luxembourgish, Letzeburgesch\"}",
    		"{\"code\":\"lg\", \"name\":\"Luganda\"}",
    		"{\"code\":\"li\", \"name\":\"Limburgish, Limburgan, Limburger\"}",
    		"{\"code\":\"ln\", \"name\":\"Lingala\"}",
    		"{\"code\":\"lo\", \"name\":\"Lao\"}",
    		"{\"code\":\"lt\", \"name\":\"Lithuanian\"}",
    		"{\"code\":\"lu\", \"name\":\"Luba-Katanga\"}",
    		"{\"code\":\"lv\", \"name\":\"Latvian\"}",
    		"{\"code\":\"mg\", \"name\":\"Malagasy\"}",
    		"{\"code\":\"mh\", \"name\":\"Marshallese\"}",
    		"{\"code\":\"mi\", \"name\":\"Maori\"}",
    		"{\"code\":\"mk\", \"name\":\"Macedonian\"}",
    		"{\"code\":\"ml\", \"name\":\"Malayalam\"}",
    		"{\"code\":\"mn\", \"name\":\"Mongolian\"}",
    		"{\"code\":\"mr\", \"name\":\"Marathi (Mara?hi)\"}",
    		"{\"code\":\"ms\", \"name\":\"Malay\"}",
    		"{\"code\":\"mt\", \"name\":\"Maltese\"}",
    		"{\"code\":\"my\", \"name\":\"Burmese\"}",
    		"{\"code\":\"na\", \"name\":\"Nauru\"}",
    		"{\"code\":\"nb\", \"name\":\"Norwegian BokmÅ¥l\"}",
    		"{\"code\":\"nd\", \"name\":\"North Ndebele\"}",
    		"{\"code\":\"ne\", \"name\":\"Nepali\"}",
    		"{\"code\":\"ng\", \"name\":\"Ndonga\"}",
    		"{\"code\":\"nl\", \"name\":\"Dutch\"}",
    		"{\"code\":\"nn\", \"name\":\"Norwegian Nynorsk\"}",
    		"{\"code\":\"no\", \"name\":\"Norwegian\"}",
    		"{\"code\":\"nr\", \"name\":\"South Ndebele\"}",
    		"{\"code\":\"nv\", \"name\":\"Navajo, Navaho\"}",
    		"{\"code\":\"ny\", \"name\":\"Chichewa; Chewa; Nyanja\"}",
    		"{\"code\":\"oc\", \"name\":\"Occitan\"}",
    		"{\"code\":\"oj\", \"name\":\"Ojibwe, Ojibwa\"}",
    		"{\"code\":\"om\", \"name\":\"Oromo\"}",
    		"{\"code\":\"or\", \"name\":\"Oriya\"}",
    		"{\"code\":\"os\", \"name\":\"Ossetian, Ossetic\"}",
    		"{\"code\":\"pa\", \"name\":\"Panjabi, Punjabi\"}",
    		"{\"code\":\"pi\", \"name\":\"Pali\"}",
    		"{\"code\":\"pl\", \"name\":\"Polish\"}",
    		"{\"code\":\"ps\", \"name\":\"Pashto, Pushto\"}",
    		"{\"code\":\"pt\", \"name\":\"Portuguese\"}",
    		"{\"code\":\"qu\", \"name\":\"Quechua\"}",
    		"{\"code\":\"rm\", \"name\":\"Romansh\"}",
    		"{\"code\":\"rn\", \"name\":\"Kirundi\"}",
    		"{\"code\":\"ro\", \"name\":\"Romanian, Moldavian, Moldovan\"}",
    		"{\"code\":\"ru\", \"name\":\"Russian\"}",
    		"{\"code\":\"rw\", \"name\":\"Kinyarwanda\"}",
    		"{\"code\":\"sa\", \"name\":\"Sanskrit (Sa?sk?ta)\"}",
    		"{\"code\":\"sc\", \"name\":\"Sardinian\"}",
    		"{\"code\":\"sd\", \"name\":\"Sindhi\"}",
    		"{\"code\":\"se\", \"name\":\"Northern Sami\"}",
    		"{\"code\":\"sg\", \"name\":\"Sango\"}",
    		"{\"code\":\"si\", \"name\":\"Sinhala, Sinhalese\"}",
    		"{\"code\":\"sk\", \"name\":\"Slovak\"}",
    		"{\"code\":\"sl\", \"name\":\"Slovene\"}",
    		"{\"code\":\"sm\", \"name\":\"Samoan\"}",
    		"{\"code\":\"sn\", \"name\":\"Shona\"}",
    		"{\"code\":\"so\", \"name\":\"Somali\"}",
    		"{\"code\":\"sq\", \"name\":\"Albanian\"}",
    		"{\"code\":\"sr\", \"name\":\"Serbian\"}",
    		"{\"code\":\"ss\", \"name\":\"Swati\"}",
    		"{\"code\":\"st\", \"name\":\"Southern Sotho\"}",
    		"{\"code\":\"su\", \"name\":\"Sundanese\"}",
    		"{\"code\":\"sv\", \"name\":\"Swedish\"}",
    		"{\"code\":\"sw\", \"name\":\"Swahili\"}",
    		"{\"code\":\"ta\", \"name\":\"Tamil\"}",
    		"{\"code\":\"te\", \"name\":\"Telugu\"}",
    		"{\"code\":\"tg\", \"name\":\"Tajik\"}",
    		"{\"code\":\"th\", \"name\":\"Thai\"}",
    		"{\"code\":\"ti\", \"name\":\"Tigrinya\"}",
    		"{\"code\":\"tk\", \"name\":\"Turkmen\"}",
    		"{\"code\":\"tl\", \"name\":\"Tagalog\"}",
    		"{\"code\":\"tn\", \"name\":\"Tswana\"}",
    		"{\"code\":\"to\", \"name\":\"Tonga (Tonga Islands)\"}",
    		"{\"code\":\"tr\", \"name\":\"Turkish\"}",
    		"{\"code\":\"ts\", \"name\":\"Tsonga\"}",
    		"{\"code\":\"tt\", \"name\":\"Tatar\"}",
    		"{\"code\":\"tw\", \"name\":\"Twi\"}",
    		"{\"code\":\"ty\", \"name\":\"Tahitian\"}",
    		"{\"code\":\"ug\", \"name\":\"Uighur, Uyghur\"}",
    		"{\"code\":\"uk\", \"name\":\"Ukrainian\"}",
    		"{\"code\":\"ur\", \"name\":\"Urdu\"}",
    		"{\"code\":\"uz\", \"name\":\"Uzbek\"}",
    		"{\"code\":\"ve\", \"name\":\"Venda\"}",
    		"{\"code\":\"vi\", \"name\":\"Vietnamese\"}",
    		"{\"code\":\"vo\", \"name\":\"VolapÅ¼k\"}",
    		"{\"code\":\"wa\", \"name\":\"Walloon\"}",
    		"{\"code\":\"wo\", \"name\":\"Wolof\"}",
    		"{\"code\":\"xh\", \"name\":\"Xhosa\"}",
    		"{\"code\":\"yi\", \"name\":\"Yiddish\"}",
    		"{\"code\":\"yo\", \"name\":\"Yoruba\"}",
    		"{\"code\":\"za\", \"name\":\"Zhuang, Chuang\"}",
    		"{\"code\":\"zh\", \"name\":\"Chinese\"}",
    		"{\"code\":\"zu\", \"name\":\"Zulu\"}"
    };

}
